var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_tests_1_1_offline =
[
    [ "DefaultOfflineManagerIntegratedTest", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_tests_1_1_offline_1_1_default_offline_manager_integrated_test.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_tests_1_1_offline_1_1_default_offline_manager_integrated_test" ],
    [ "OfflineAuditServiceIntegratedTest", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_tests_1_1_offline_1_1_offline_audit_service_integrated_test.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_tests_1_1_offline_1_1_offline_audit_service_integrated_test" ]
];