var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_web_api =
[
    [ "Controllers", "namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_web_api_1_1_controllers.html", "namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_web_api_1_1_controllers" ]
];