var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_cors =
[
    [ "GenericCorsPolicyProvider", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_cors_1_1_generic_cors_policy_provider.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_cors_1_1_generic_cors_policy_provider" ]
];