var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_events =
[
    [ "IEventHandlerContainer", "interface_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_events_1_1_i_event_handler_container.html", "interface_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_events_1_1_i_event_handler_container" ]
];