var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_handlers =
[
    [ "ExtendedODataPathHandler", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_handlers_1_1_extended_o_data_path_handler.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_handlers_1_1_extended_o_data_path_handler" ],
    [ "PostPatchHandler", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_handlers_1_1_post_patch_handler.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_handlers_1_1_post_patch_handler" ]
];