var namespace_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_controllers =
[
    [ "BaseODataController", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_controllers_1_1_base_o_data_controller.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_controllers_1_1_base_o_data_controller" ],
    [ "DataObjectController", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_controllers_1_1_data_object_controller.html", "class_new_platform_1_1_flexberry_1_1_o_r_m_1_1_o_data_service_1_1_controllers_1_1_data_object_controller" ]
];