//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// AgrClass2.
    /// </summary>
    // *** Start programmer edit section *** (AgrClass2 CustomAttributes)

    // *** End programmer edit section *** (AgrClass2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class AgrClass2 : ICSSoft.STORMNET.DataObject
    {
        
        private string fAgrCl2Name;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailsClass2 fDetailsClass2;
        
        // *** Start programmer edit section *** (AgrClass2 CustomMembers)

        // *** End programmer edit section *** (AgrClass2 CustomMembers)

        
        /// <summary>
        /// AgrCl2Name.
        /// </summary>
        // *** Start programmer edit section *** (AgrClass2.AgrCl2Name CustomAttributes)

        // *** End programmer edit section *** (AgrClass2.AgrCl2Name CustomAttributes)
        [StrLen(255)]
        public virtual string AgrCl2Name
        {
            get
            {
                // *** Start programmer edit section *** (AgrClass2.AgrCl2Name Get start)

                // *** End programmer edit section *** (AgrClass2.AgrCl2Name Get start)
                string result = this.fAgrCl2Name;
                // *** Start programmer edit section *** (AgrClass2.AgrCl2Name Get end)

                // *** End programmer edit section *** (AgrClass2.AgrCl2Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AgrClass2.AgrCl2Name Set start)

                // *** End programmer edit section *** (AgrClass2.AgrCl2Name Set start)
                this.fAgrCl2Name = value;
                // *** Start programmer edit section *** (AgrClass2.AgrCl2Name Set end)

                // *** End programmer edit section *** (AgrClass2.AgrCl2Name Set end)
            }
        }
        
        /// <summary>
        /// AgrClass2.
        /// </summary>
        // *** Start programmer edit section *** (AgrClass2.DetailsClass2 CustomAttributes)

        // *** End programmer edit section *** (AgrClass2.DetailsClass2 CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailsClass2 DetailsClass2
        {
            get
            {
                // *** Start programmer edit section *** (AgrClass2.DetailsClass2 Get start)

                // *** End programmer edit section *** (AgrClass2.DetailsClass2 Get start)
                if ((this.fDetailsClass2 == null))
                {
                    this.fDetailsClass2 = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailsClass2(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailsClass2 result = this.fDetailsClass2;
                // *** Start programmer edit section *** (AgrClass2.DetailsClass2 Get end)

                // *** End programmer edit section *** (AgrClass2.DetailsClass2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AgrClass2.DetailsClass2 Set start)

                // *** End programmer edit section *** (AgrClass2.DetailsClass2 Set start)
                this.fDetailsClass2 = value;
                // *** Start programmer edit section *** (AgrClass2.DetailsClass2 Set end)

                // *** End programmer edit section *** (AgrClass2.DetailsClass2 Set end)
            }
        }
    }
}
