//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// AgregatorWithSameMAndD.
    /// </summary>
    // *** Start programmer edit section *** (AgregatorWithSameMAndD CustomAttributes)

    // *** End programmer edit section *** (AgregatorWithSameMAndD CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class AgregatorWithSameMAndD : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailAndMaster fMaster;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailAndMaster fDetails;

        // *** Start programmer edit section *** (AgregatorWithSameMAndD CustomMembers)

        // *** End programmer edit section *** (AgregatorWithSameMAndD CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (AgregatorWithSameMAndD.Name CustomAttributes)

        // *** End programmer edit section *** (AgregatorWithSameMAndD.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Name Get start)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Name Get end)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Name Set start)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Name Set end)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Name Set end)
            }
        }

        /// <summary>
        /// AgregatorWithSameMAndD.
        /// </summary>
        // *** Start programmer edit section *** (AgregatorWithSameMAndD.Master CustomAttributes)

        // *** End programmer edit section *** (AgregatorWithSameMAndD.Master CustomAttributes)
        [PropertyStorage(new string[] {
                "Master"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailAndMaster Master
        {
            get
            {
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Master Get start)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Master Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailAndMaster result = this.fMaster;
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Master Get end)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Master Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Master Set start)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Master Set start)
                this.fMaster = value;
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Master Set end)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Master Set end)
            }
        }

        /// <summary>
        /// AgregatorWithSameMAndD.
        /// </summary>
        // *** Start programmer edit section *** (AgregatorWithSameMAndD.Details CustomAttributes)

        // *** End programmer edit section *** (AgregatorWithSameMAndD.Details CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailAndMaster Details
        {
            get
            {
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Details Get start)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Details Get start)
                if ((this.fDetails == null))
                {
                    this.fDetails = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailAndMaster(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailAndMaster result = this.fDetails;
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Details Get end)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Details Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Details Set start)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Details Set start)
                this.fDetails = value;
                // *** Start programmer edit section *** (AgregatorWithSameMAndD.Details Set end)

                // *** End programmer edit section *** (AgregatorWithSameMAndD.Details Set end)
            }
        }
    }
}

