//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// BaseLegoBlock.
    /// </summary>
    // *** Start programmer edit section *** (BaseLegoBlock CustomAttributes)

    // *** End programmer edit section *** (BaseLegoBlock CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class BaseLegoBlock : ICSSoft.STORMNET.DataObject
    {

        private int fBlockId;

        private string fName;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockColor fColor;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoPatent fPatents;

        // *** Start programmer edit section *** (BaseLegoBlock CustomMembers)
        [NotStored]
        public virtual string AssocType
        {
            get
            {
                return GetType().Name;
            }
        }
        // *** End programmer edit section *** (BaseLegoBlock CustomMembers)


        /// <summary>
        /// BlockId.
        /// </summary>
        // *** Start programmer edit section *** (BaseLegoBlock.BlockId CustomAttributes)

        // *** End programmer edit section *** (BaseLegoBlock.BlockId CustomAttributes)
        public virtual int BlockId
        {
            get
            {
                // *** Start programmer edit section *** (BaseLegoBlock.BlockId Get start)

                // *** End programmer edit section *** (BaseLegoBlock.BlockId Get start)
                int result = this.fBlockId;
                // *** Start programmer edit section *** (BaseLegoBlock.BlockId Get end)

                // *** End programmer edit section *** (BaseLegoBlock.BlockId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BaseLegoBlock.BlockId Set start)

                // *** End programmer edit section *** (BaseLegoBlock.BlockId Set start)
                this.fBlockId = value;
                // *** Start programmer edit section *** (BaseLegoBlock.BlockId Set end)

                // *** End programmer edit section *** (BaseLegoBlock.BlockId Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (BaseLegoBlock.Name CustomAttributes)

        // *** End programmer edit section *** (BaseLegoBlock.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (BaseLegoBlock.Name Get start)

                // *** End programmer edit section *** (BaseLegoBlock.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (BaseLegoBlock.Name Get end)

                // *** End programmer edit section *** (BaseLegoBlock.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BaseLegoBlock.Name Set start)

                // *** End programmer edit section *** (BaseLegoBlock.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (BaseLegoBlock.Name Set end)

                // *** End programmer edit section *** (BaseLegoBlock.Name Set end)
            }
        }

        /// <summary>
        /// BaseLegoBlock.
        /// </summary>
        // *** Start programmer edit section *** (BaseLegoBlock.Color CustomAttributes)

        // *** End programmer edit section *** (BaseLegoBlock.Color CustomAttributes)
        [PropertyStorage(new string[] {
                "Color"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockColor Color
        {
            get
            {
                // *** Start programmer edit section *** (BaseLegoBlock.Color Get start)

                // *** End programmer edit section *** (BaseLegoBlock.Color Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockColor result = this.fColor;
                // *** Start programmer edit section *** (BaseLegoBlock.Color Get end)

                // *** End programmer edit section *** (BaseLegoBlock.Color Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BaseLegoBlock.Color Set start)

                // *** End programmer edit section *** (BaseLegoBlock.Color Set start)
                this.fColor = value;
                // *** Start programmer edit section *** (BaseLegoBlock.Color Set end)

                // *** End programmer edit section *** (BaseLegoBlock.Color Set end)
            }
        }

        /// <summary>
        /// BaseLegoBlock.
        /// </summary>
        // *** Start programmer edit section *** (BaseLegoBlock.Patents CustomAttributes)

        // *** End programmer edit section *** (BaseLegoBlock.Patents CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoPatent Patents
        {
            get
            {
                // *** Start programmer edit section *** (BaseLegoBlock.Patents Get start)

                // *** End programmer edit section *** (BaseLegoBlock.Patents Get start)
                if ((this.fPatents == null))
                {
                    this.fPatents = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoPatent(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoPatent result = this.fPatents;
                // *** Start programmer edit section *** (BaseLegoBlock.Patents Get end)

                // *** End programmer edit section *** (BaseLegoBlock.Patents Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BaseLegoBlock.Patents Set start)

                // *** End programmer edit section *** (BaseLegoBlock.Patents Set start)
                this.fPatents = value;
                // *** Start programmer edit section *** (BaseLegoBlock.Patents Set end)

                // *** End programmer edit section *** (BaseLegoBlock.Patents Set end)
            }
        }
    }
}

