//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DetailsClass1.
    /// </summary>
    // *** Start programmer edit section *** (DetailsClass1 CustomAttributes)

    // *** End programmer edit section *** (DetailsClass1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class DetailsClass1 : ICSSoft.STORMNET.DataObject
    {
        
        private string fDetailCl1Name;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailsClass2 fDetailsClass2;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.AgrClass1 fAgrClass1;
        
        // *** Start programmer edit section *** (DetailsClass1 CustomMembers)

        // *** End programmer edit section *** (DetailsClass1 CustomMembers)

        
        /// <summary>
        /// DetailCl1Name.
        /// </summary>
        // *** Start programmer edit section *** (DetailsClass1.DetailCl1Name CustomAttributes)

        // *** End programmer edit section *** (DetailsClass1.DetailCl1Name CustomAttributes)
        [StrLen(255)]
        public virtual string DetailCl1Name
        {
            get
            {
                // *** Start programmer edit section *** (DetailsClass1.DetailCl1Name Get start)

                // *** End programmer edit section *** (DetailsClass1.DetailCl1Name Get start)
                string result = this.fDetailCl1Name;
                // *** Start programmer edit section *** (DetailsClass1.DetailCl1Name Get end)

                // *** End programmer edit section *** (DetailsClass1.DetailCl1Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailsClass1.DetailCl1Name Set start)

                // *** End programmer edit section *** (DetailsClass1.DetailCl1Name Set start)
                this.fDetailCl1Name = value;
                // *** Start programmer edit section *** (DetailsClass1.DetailCl1Name Set end)

                // *** End programmer edit section *** (DetailsClass1.DetailCl1Name Set end)
            }
        }
        
        /// <summary>
        /// DetailsClass1.
        /// </summary>
        // *** Start programmer edit section *** (DetailsClass1.DetailsClass2 CustomAttributes)

        // *** End programmer edit section *** (DetailsClass1.DetailsClass2 CustomAttributes)
        [PropertyStorage(new string[] {
                "DetailsClass2"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailsClass2 DetailsClass2
        {
            get
            {
                // *** Start programmer edit section *** (DetailsClass1.DetailsClass2 Get start)

                // *** End programmer edit section *** (DetailsClass1.DetailsClass2 Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailsClass2 result = this.fDetailsClass2;
                // *** Start programmer edit section *** (DetailsClass1.DetailsClass2 Get end)

                // *** End programmer edit section *** (DetailsClass1.DetailsClass2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailsClass1.DetailsClass2 Set start)

                // *** End programmer edit section *** (DetailsClass1.DetailsClass2 Set start)
                this.fDetailsClass2 = value;
                // *** Start programmer edit section *** (DetailsClass1.DetailsClass2 Set end)

                // *** End programmer edit section *** (DetailsClass1.DetailsClass2 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.AgrClass1.
        /// </summary>
        // *** Start programmer edit section *** (DetailsClass1.AgrClass1 CustomAttributes)

        // *** End programmer edit section *** (DetailsClass1.AgrClass1 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "AgrClass1"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.AgrClass1 AgrClass1
        {
            get
            {
                // *** Start programmer edit section *** (DetailsClass1.AgrClass1 Get start)

                // *** End programmer edit section *** (DetailsClass1.AgrClass1 Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.AgrClass1 result = this.fAgrClass1;
                // *** Start programmer edit section *** (DetailsClass1.AgrClass1 Get end)

                // *** End programmer edit section *** (DetailsClass1.AgrClass1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailsClass1.AgrClass1 Set start)

                // *** End programmer edit section *** (DetailsClass1.AgrClass1 Set start)
                this.fAgrClass1 = value;
                // *** Start programmer edit section *** (DetailsClass1.AgrClass1 Set end)

                // *** End programmer edit section *** (DetailsClass1.AgrClass1 Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of DetailsClass1.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDetailsClass1 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfDetailsClass1 CustomAttributes)
    public class DetailArrayOfDetailsClass1 : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailsClass1 members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailsClass1 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type DetailsClass1 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type DetailsClass1.
        /// </summary>
        public DetailArrayOfDetailsClass1(NewPlatform.Flexberry.ORM.ODataService.Tests.AgrClass1 fAgrClass1) : 
                base(typeof(DetailsClass1), ((ICSSoft.STORMNET.DataObject)(fAgrClass1)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.ODataService.Tests.DetailsClass1 this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.DetailsClass1)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.DetailsClass1 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
