//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// DetailAndMaster.
    /// </summary>
    // *** Start programmer edit section *** (DetailAndMaster CustomAttributes)

    // *** End programmer edit section *** (DetailAndMaster CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class DetailAndMaster : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.AgregatorWithSameMAndD fAgregator;

        // *** Start programmer edit section *** (DetailAndMaster CustomMembers)

        // *** End programmer edit section *** (DetailAndMaster CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (DetailAndMaster.Name CustomAttributes)

        // *** End programmer edit section *** (DetailAndMaster.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (DetailAndMaster.Name Get start)

                // *** End programmer edit section *** (DetailAndMaster.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (DetailAndMaster.Name Get end)

                // *** End programmer edit section *** (DetailAndMaster.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailAndMaster.Name Set start)

                // *** End programmer edit section *** (DetailAndMaster.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (DetailAndMaster.Name Set end)

                // *** End programmer edit section *** (DetailAndMaster.Name Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.AgregatorWithSameMAndD.
        /// </summary>
        // *** Start programmer edit section *** (DetailAndMaster.Agregator CustomAttributes)

        // *** End programmer edit section *** (DetailAndMaster.Agregator CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Agregator"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.AgregatorWithSameMAndD Agregator
        {
            get
            {
                // *** Start programmer edit section *** (DetailAndMaster.Agregator Get start)

                // *** End programmer edit section *** (DetailAndMaster.Agregator Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.AgregatorWithSameMAndD result = this.fAgregator;
                // *** Start programmer edit section *** (DetailAndMaster.Agregator Get end)

                // *** End programmer edit section *** (DetailAndMaster.Agregator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (DetailAndMaster.Agregator Set start)

                // *** End programmer edit section *** (DetailAndMaster.Agregator Set start)
                this.fAgregator = value;
                // *** Start programmer edit section *** (DetailAndMaster.Agregator Set end)

                // *** End programmer edit section *** (DetailAndMaster.Agregator Set end)
            }
        }
    }

    /// <summary>
    /// Detail array of DetailAndMaster.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfDetailAndMaster CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfDetailAndMaster CustomAttributes)
    public class DetailArrayOfDetailAndMaster : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailAndMaster members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfDetailAndMaster members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type DetailAndMaster by index.
        /// </summary>
        /// <summary>
        /// Adds object with type DetailAndMaster.
        /// </summary>
        public DetailArrayOfDetailAndMaster(NewPlatform.Flexberry.ORM.ODataService.Tests.AgregatorWithSameMAndD fAgregatorWithSameMAndD) : 
                base(typeof(DetailAndMaster), ((ICSSoft.STORMNET.DataObject)(fAgregatorWithSameMAndD)))
        {
        }

        public NewPlatform.Flexberry.ORM.ODataService.Tests.DetailAndMaster this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.DetailAndMaster)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.DetailAndMaster dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

