//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// FirstLevel.
    /// </summary>
    // *** Start programmer edit section *** (FirstLevel CustomAttributes)

    // *** End programmer edit section *** (FirstLevel CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class FirstLevel : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel1 fSecondLevel1;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel2 fSecondLevel2;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.TestConfiguration fTestConfiguration;

        // *** Start programmer edit section *** (FirstLevel CustomMembers)

        // *** End programmer edit section *** (FirstLevel CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (FirstLevel.Name CustomAttributes)

        // *** End programmer edit section *** (FirstLevel.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (FirstLevel.Name Get start)

                // *** End programmer edit section *** (FirstLevel.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (FirstLevel.Name Get end)

                // *** End programmer edit section *** (FirstLevel.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FirstLevel.Name Set start)

                // *** End programmer edit section *** (FirstLevel.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (FirstLevel.Name Set end)

                // *** End programmer edit section *** (FirstLevel.Name Set end)
            }
        }

        /// <summary>
        /// FirstLevel.
        /// </summary>
        // *** Start programmer edit section *** (FirstLevel.SecondLevel1 CustomAttributes)

        // *** End programmer edit section *** (FirstLevel.SecondLevel1 CustomAttributes)
        [TypeUsage(new System.Type[] {
                typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1),
                typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.TestClass)})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel1 SecondLevel1
        {
            get
            {
                // *** Start programmer edit section *** (FirstLevel.SecondLevel1 Get start)

                // *** End programmer edit section *** (FirstLevel.SecondLevel1 Get start)
                if ((this.fSecondLevel1 == null))
                {
                    this.fSecondLevel1 = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel1(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel1 result = this.fSecondLevel1;
                // *** Start programmer edit section *** (FirstLevel.SecondLevel1 Get end)

                // *** End programmer edit section *** (FirstLevel.SecondLevel1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FirstLevel.SecondLevel1 Set start)

                // *** End programmer edit section *** (FirstLevel.SecondLevel1 Set start)
                this.fSecondLevel1 = value;
                // *** Start programmer edit section *** (FirstLevel.SecondLevel1 Set end)

                // *** End programmer edit section *** (FirstLevel.SecondLevel1 Set end)
            }
        }

        /// <summary>
        /// FirstLevel.
        /// </summary>
        // *** Start programmer edit section *** (FirstLevel.SecondLevel2 CustomAttributes)

        // *** End programmer edit section *** (FirstLevel.SecondLevel2 CustomAttributes)
        [TypeUsage(new System.Type[] {
                typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel2),
                typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.TestAssociation)})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel2 SecondLevel2
        {
            get
            {
                // *** Start programmer edit section *** (FirstLevel.SecondLevel2 Get start)

                // *** End programmer edit section *** (FirstLevel.SecondLevel2 Get start)
                if ((this.fSecondLevel2 == null))
                {
                    this.fSecondLevel2 = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel2(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel2 result = this.fSecondLevel2;
                // *** Start programmer edit section *** (FirstLevel.SecondLevel2 Get end)

                // *** End programmer edit section *** (FirstLevel.SecondLevel2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FirstLevel.SecondLevel2 Set start)

                // *** End programmer edit section *** (FirstLevel.SecondLevel2 Set start)
                this.fSecondLevel2 = value;
                // *** Start programmer edit section *** (FirstLevel.SecondLevel2 Set end)

                // *** End programmer edit section *** (FirstLevel.SecondLevel2 Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.TestConfiguration.
        /// </summary>
        // *** Start programmer edit section *** (FirstLevel.TestConfiguration CustomAttributes)

        // *** End programmer edit section *** (FirstLevel.TestConfiguration CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "TestConfiguration"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.TestConfiguration TestConfiguration
        {
            get
            {
                // *** Start programmer edit section *** (FirstLevel.TestConfiguration Get start)

                // *** End programmer edit section *** (FirstLevel.TestConfiguration Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.TestConfiguration result = this.fTestConfiguration;
                // *** Start programmer edit section *** (FirstLevel.TestConfiguration Get end)

                // *** End programmer edit section *** (FirstLevel.TestConfiguration Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FirstLevel.TestConfiguration Set start)

                // *** End programmer edit section *** (FirstLevel.TestConfiguration Set start)
                this.fTestConfiguration = value;
                // *** Start programmer edit section *** (FirstLevel.TestConfiguration Set end)

                // *** End programmer edit section *** (FirstLevel.TestConfiguration Set end)
            }
        }
    }

    /// <summary>
    /// Detail array of FirstLevel.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfFirstLevel CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfFirstLevel CustomAttributes)
    public class DetailArrayOfFirstLevel : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfFirstLevel members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfFirstLevel members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type FirstLevel by index.
        /// </summary>
        /// <summary>
        /// Adds object with type FirstLevel.
        /// </summary>
        public DetailArrayOfFirstLevel(NewPlatform.Flexberry.ORM.ODataService.Tests.TestConfiguration fTestConfiguration) : 
                base(typeof(FirstLevel), ((ICSSoft.STORMNET.DataObject)(fTestConfiguration)))
        {
        }

        public NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

