//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoMaterial.
    /// </summary>
    // *** Start programmer edit section *** (LegoMaterial CustomAttributes)

    // *** End programmer edit section *** (LegoMaterial CustomAttributes)
    [PublishName("LegoMaterial")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoMaterial : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        // *** Start programmer edit section *** (LegoMaterial CustomMembers)

        // *** End programmer edit section *** (LegoMaterial CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (LegoMaterial.Name CustomAttributes)

        // *** End programmer edit section *** (LegoMaterial.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (LegoMaterial.Name Get start)

                // *** End programmer edit section *** (LegoMaterial.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (LegoMaterial.Name Get end)

                // *** End programmer edit section *** (LegoMaterial.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoMaterial.Name Set start)

                // *** End programmer edit section *** (LegoMaterial.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (LegoMaterial.Name Set end)

                // *** End programmer edit section *** (LegoMaterial.Name Set end)
            }
        }
    }
}

