//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoPatent.
    /// </summary>
    // *** Start programmer edit section *** (LegoPatent CustomAttributes)

    // *** End programmer edit section *** (LegoPatent CustomAttributes)
    [PublishName("LegoPatent")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoPatent : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private System.DateTime fDate;
        
        private string fAuthors;
        
        private string fDescription;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.BaseLegoBlock fBaseLegoBlock;
        
        // *** Start programmer edit section *** (LegoPatent CustomMembers)

        // *** End programmer edit section *** (LegoPatent CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (LegoPatent.Name CustomAttributes)

        // *** End programmer edit section *** (LegoPatent.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (LegoPatent.Name Get start)

                // *** End programmer edit section *** (LegoPatent.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (LegoPatent.Name Get end)

                // *** End programmer edit section *** (LegoPatent.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPatent.Name Set start)

                // *** End programmer edit section *** (LegoPatent.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (LegoPatent.Name Set end)

                // *** End programmer edit section *** (LegoPatent.Name Set end)
            }
        }
        
        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (LegoPatent.Date CustomAttributes)

        // *** End programmer edit section *** (LegoPatent.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (LegoPatent.Date Get start)

                // *** End programmer edit section *** (LegoPatent.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (LegoPatent.Date Get end)

                // *** End programmer edit section *** (LegoPatent.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPatent.Date Set start)

                // *** End programmer edit section *** (LegoPatent.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (LegoPatent.Date Set end)

                // *** End programmer edit section *** (LegoPatent.Date Set end)
            }
        }
        
        /// <summary>
        /// Authors.
        /// </summary>
        // *** Start programmer edit section *** (LegoPatent.Authors CustomAttributes)

        // *** End programmer edit section *** (LegoPatent.Authors CustomAttributes)
        [StrLen(255)]
        public virtual string Authors
        {
            get
            {
                // *** Start programmer edit section *** (LegoPatent.Authors Get start)

                // *** End programmer edit section *** (LegoPatent.Authors Get start)
                string result = this.fAuthors;
                // *** Start programmer edit section *** (LegoPatent.Authors Get end)

                // *** End programmer edit section *** (LegoPatent.Authors Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPatent.Authors Set start)

                // *** End programmer edit section *** (LegoPatent.Authors Set start)
                this.fAuthors = value;
                // *** Start programmer edit section *** (LegoPatent.Authors Set end)

                // *** End programmer edit section *** (LegoPatent.Authors Set end)
            }
        }
        
        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (LegoPatent.Description CustomAttributes)

        // *** End programmer edit section *** (LegoPatent.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (LegoPatent.Description Get start)

                // *** End programmer edit section *** (LegoPatent.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (LegoPatent.Description Get end)

                // *** End programmer edit section *** (LegoPatent.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPatent.Description Set start)

                // *** End programmer edit section *** (LegoPatent.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (LegoPatent.Description Set end)

                // *** End programmer edit section *** (LegoPatent.Description Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.BaseLegoBlock.
        /// </summary>
        // *** Start programmer edit section *** (LegoPatent.BaseLegoBlock CustomAttributes)

        // *** End programmer edit section *** (LegoPatent.BaseLegoBlock CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "LegoBlock",
                "LegoDevice"})]
        [TypeUsage(new string[] {
                "NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlock",
                "NewPlatform.Flexberry.ORM.ODataService.Tests.LegoDevice"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.BaseLegoBlock BaseLegoBlock
        {
            get
            {
                // *** Start programmer edit section *** (LegoPatent.BaseLegoBlock Get start)

                // *** End programmer edit section *** (LegoPatent.BaseLegoBlock Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.BaseLegoBlock result = this.fBaseLegoBlock;
                // *** Start programmer edit section *** (LegoPatent.BaseLegoBlock Get end)

                // *** End programmer edit section *** (LegoPatent.BaseLegoBlock Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPatent.BaseLegoBlock Set start)

                // *** End programmer edit section *** (LegoPatent.BaseLegoBlock Set start)
                this.fBaseLegoBlock = value;
                // *** Start programmer edit section *** (LegoPatent.BaseLegoBlock Set end)

                // *** End programmer edit section *** (LegoPatent.BaseLegoBlock Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of LegoPatent.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLegoPatent CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLegoPatent CustomAttributes)
    public class DetailArrayOfLegoPatent : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoPatent members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoPatent members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LegoPatent by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LegoPatent.
        /// </summary>
        public DetailArrayOfLegoPatent(NewPlatform.Flexberry.ORM.ODataService.Tests.BaseLegoBlock fBaseLegoBlock) : 
                base(typeof(LegoPatent), ((ICSSoft.STORMNET.DataObject)(fBaseLegoBlock)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.ODataService.Tests.LegoPatent this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.LegoPatent)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.LegoPatent dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
