//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoSocketStandard.
    /// </summary>
    // *** Start programmer edit section *** (LegoSocketStandard CustomAttributes)

    // *** End programmer edit section *** (LegoSocketStandard CustomAttributes)
    [PublishName("LegoSocketStandard")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoSocketStandard : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (LegoSocketStandard CustomMembers)

        // *** End programmer edit section *** (LegoSocketStandard CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (LegoSocketStandard.Name CustomAttributes)

        // *** End programmer edit section *** (LegoSocketStandard.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (LegoSocketStandard.Name Get start)

                // *** End programmer edit section *** (LegoSocketStandard.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (LegoSocketStandard.Name Get end)

                // *** End programmer edit section *** (LegoSocketStandard.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoSocketStandard.Name Set start)

                // *** End programmer edit section *** (LegoSocketStandard.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (LegoSocketStandard.Name Set end)

                // *** End programmer edit section *** (LegoSocketStandard.Name Set end)
            }
        }
    }
}
