//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoBlockTopPanelHole.
    /// </summary>
    // *** Start programmer edit section *** (LegoBlockTopPanelHole CustomAttributes)

    // *** End programmer edit section *** (LegoBlockTopPanelHole CustomAttributes)
    [PublishName("LegoBlockTopPanelHole")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoBlockTopPanelHole : ICSSoft.STORMNET.DataObject
    {
        
        private string fPosition;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockTopPanel fTopPanel;
        
        // *** Start programmer edit section *** (LegoBlockTopPanelHole CustomMembers)

        // *** End programmer edit section *** (LegoBlockTopPanelHole CustomMembers)

        
        /// <summary>
        /// Position.
        /// </summary>
        // *** Start programmer edit section *** (LegoBlockTopPanelHole.Position CustomAttributes)

        // *** End programmer edit section *** (LegoBlockTopPanelHole.Position CustomAttributes)
        [StrLen(255)]
        public virtual string Position
        {
            get
            {
                // *** Start programmer edit section *** (LegoBlockTopPanelHole.Position Get start)

                // *** End programmer edit section *** (LegoBlockTopPanelHole.Position Get start)
                string result = this.fPosition;
                // *** Start programmer edit section *** (LegoBlockTopPanelHole.Position Get end)

                // *** End programmer edit section *** (LegoBlockTopPanelHole.Position Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoBlockTopPanelHole.Position Set start)

                // *** End programmer edit section *** (LegoBlockTopPanelHole.Position Set start)
                this.fPosition = value;
                // *** Start programmer edit section *** (LegoBlockTopPanelHole.Position Set end)

                // *** End programmer edit section *** (LegoBlockTopPanelHole.Position Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockTopPanel.
        /// </summary>
        // *** Start programmer edit section *** (LegoBlockTopPanelHole.TopPanel CustomAttributes)

        // *** End programmer edit section *** (LegoBlockTopPanelHole.TopPanel CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "TopPanel"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockTopPanel TopPanel
        {
            get
            {
                // *** Start programmer edit section *** (LegoBlockTopPanelHole.TopPanel Get start)

                // *** End programmer edit section *** (LegoBlockTopPanelHole.TopPanel Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockTopPanel result = this.fTopPanel;
                // *** Start programmer edit section *** (LegoBlockTopPanelHole.TopPanel Get end)

                // *** End programmer edit section *** (LegoBlockTopPanelHole.TopPanel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoBlockTopPanelHole.TopPanel Set start)

                // *** End programmer edit section *** (LegoBlockTopPanelHole.TopPanel Set start)
                this.fTopPanel = value;
                // *** Start programmer edit section *** (LegoBlockTopPanelHole.TopPanel Set end)

                // *** End programmer edit section *** (LegoBlockTopPanelHole.TopPanel Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of LegoBlockTopPanelHole.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLegoBlockTopPanelHole CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLegoBlockTopPanelHole CustomAttributes)
    public class DetailArrayOfLegoBlockTopPanelHole : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoBlockTopPanelHole members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoBlockTopPanelHole members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LegoBlockTopPanelHole by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LegoBlockTopPanelHole.
        /// </summary>
        public DetailArrayOfLegoBlockTopPanelHole(NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockTopPanel fLegoBlockTopPanel) : 
                base(typeof(LegoBlockTopPanelHole), ((ICSSoft.STORMNET.DataObject)(fLegoBlockTopPanel)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockTopPanelHole this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockTopPanelHole)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockTopPanelHole dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
