//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoPanelAngle.
    /// </summary>
    // *** Start programmer edit section *** (LegoPanelAngle CustomAttributes)

    // *** End programmer edit section *** (LegoPanelAngle CustomAttributes)
    [PublishName("LegoPanelAngle")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoPanelAngle : ICSSoft.STORMNET.DataObject
    {

        private int fAngle;

        private string fName;

        // *** Start programmer edit section *** (LegoPanelAngle CustomMembers)

        // *** End programmer edit section *** (LegoPanelAngle CustomMembers)


        /// <summary>
        /// Angle.
        /// </summary>
        // *** Start programmer edit section *** (LegoPanelAngle.Angle CustomAttributes)

        // *** End programmer edit section *** (LegoPanelAngle.Angle CustomAttributes)
        public virtual int Angle
        {
            get
            {
                // *** Start programmer edit section *** (LegoPanelAngle.Angle Get start)

                // *** End programmer edit section *** (LegoPanelAngle.Angle Get start)
                int result = this.fAngle;
                // *** Start programmer edit section *** (LegoPanelAngle.Angle Get end)

                // *** End programmer edit section *** (LegoPanelAngle.Angle Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPanelAngle.Angle Set start)

                // *** End programmer edit section *** (LegoPanelAngle.Angle Set start)
                this.fAngle = value;
                // *** Start programmer edit section *** (LegoPanelAngle.Angle Set end)

                // *** End programmer edit section *** (LegoPanelAngle.Angle Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (LegoPanelAngle.Name CustomAttributes)

        // *** End programmer edit section *** (LegoPanelAngle.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (LegoPanelAngle.Name Get start)

                // *** End programmer edit section *** (LegoPanelAngle.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (LegoPanelAngle.Name Get end)

                // *** End programmer edit section *** (LegoPanelAngle.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPanelAngle.Name Set start)

                // *** End programmer edit section *** (LegoPanelAngle.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (LegoPanelAngle.Name Set end)

                // *** End programmer edit section *** (LegoPanelAngle.Name Set end)
            }
        }
    }
}

