//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoPanelAngle.
    /// </summary>
    // *** Start programmer edit section *** (LegoPanelAngle CustomAttributes)

    // *** End programmer edit section *** (LegoPanelAngle CustomAttributes)
    [PublishName("LegoPanelAngle")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoPanelAngle : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private int fAngle;
        
        // *** Start programmer edit section *** (LegoPanelAngle CustomMembers)

        // *** End programmer edit section *** (LegoPanelAngle CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (LegoPanelAngle.Name CustomAttributes)

        // *** End programmer edit section *** (LegoPanelAngle.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (LegoPanelAngle.Name Get start)

                // *** End programmer edit section *** (LegoPanelAngle.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (LegoPanelAngle.Name Get end)

                // *** End programmer edit section *** (LegoPanelAngle.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPanelAngle.Name Set start)

                // *** End programmer edit section *** (LegoPanelAngle.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (LegoPanelAngle.Name Set end)

                // *** End programmer edit section *** (LegoPanelAngle.Name Set end)
            }
        }
        
        /// <summary>
        /// Angle.
        /// </summary>
        // *** Start programmer edit section *** (LegoPanelAngle.Angle CustomAttributes)

        // *** End programmer edit section *** (LegoPanelAngle.Angle CustomAttributes)
        public virtual int Angle
        {
            get
            {
                // *** Start programmer edit section *** (LegoPanelAngle.Angle Get start)

                // *** End programmer edit section *** (LegoPanelAngle.Angle Get start)
                int result = this.fAngle;
                // *** Start programmer edit section *** (LegoPanelAngle.Angle Get end)

                // *** End programmer edit section *** (LegoPanelAngle.Angle Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoPanelAngle.Angle Set start)

                // *** End programmer edit section *** (LegoPanelAngle.Angle Set start)
                this.fAngle = value;
                // *** Start programmer edit section *** (LegoPanelAngle.Angle Set end)

                // *** End programmer edit section *** (LegoPanelAngle.Angle Set end)
            }
        }
    }
}
