//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoBlockCustomPanel.
    /// </summary>
    // *** Start programmer edit section *** (LegoBlockCustomPanel CustomAttributes)

    // *** End programmer edit section *** (LegoBlockCustomPanel CustomAttributes)
    [PublishName("LegoBlockCustomPanel")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoBlockCustomPanel : ICSSoft.STORMNET.DataObject
    {
        
        private string fOrientation;
        
        private string fPosition;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.LegoPanelAngle fPanelAngle;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlock fBlock;
        
        // *** Start programmer edit section *** (LegoBlockCustomPanel CustomMembers)

        // *** End programmer edit section *** (LegoBlockCustomPanel CustomMembers)

        
        /// <summary>
        /// Orientation.
        /// </summary>
        // *** Start programmer edit section *** (LegoBlockCustomPanel.Orientation CustomAttributes)

        // *** End programmer edit section *** (LegoBlockCustomPanel.Orientation CustomAttributes)
        [StrLen(255)]
        public virtual string Orientation
        {
            get
            {
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Orientation Get start)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Orientation Get start)
                string result = this.fOrientation;
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Orientation Get end)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Orientation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Orientation Set start)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Orientation Set start)
                this.fOrientation = value;
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Orientation Set end)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Orientation Set end)
            }
        }
        
        /// <summary>
        /// Position.
        /// </summary>
        // *** Start programmer edit section *** (LegoBlockCustomPanel.Position CustomAttributes)

        // *** End programmer edit section *** (LegoBlockCustomPanel.Position CustomAttributes)
        [StrLen(255)]
        public virtual string Position
        {
            get
            {
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Position Get start)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Position Get start)
                string result = this.fPosition;
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Position Get end)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Position Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Position Set start)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Position Set start)
                this.fPosition = value;
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Position Set end)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Position Set end)
            }
        }
        
        /// <summary>
        /// LegoBlockCustomPanel.
        /// </summary>
        // *** Start programmer edit section *** (LegoBlockCustomPanel.PanelAngle CustomAttributes)

        // *** End programmer edit section *** (LegoBlockCustomPanel.PanelAngle CustomAttributes)
        [PropertyStorage(new string[] {
                "PanelAngle"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.LegoPanelAngle PanelAngle
        {
            get
            {
                // *** Start programmer edit section *** (LegoBlockCustomPanel.PanelAngle Get start)

                // *** End programmer edit section *** (LegoBlockCustomPanel.PanelAngle Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.LegoPanelAngle result = this.fPanelAngle;
                // *** Start programmer edit section *** (LegoBlockCustomPanel.PanelAngle Get end)

                // *** End programmer edit section *** (LegoBlockCustomPanel.PanelAngle Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoBlockCustomPanel.PanelAngle Set start)

                // *** End programmer edit section *** (LegoBlockCustomPanel.PanelAngle Set start)
                this.fPanelAngle = value;
                // *** Start programmer edit section *** (LegoBlockCustomPanel.PanelAngle Set end)

                // *** End programmer edit section *** (LegoBlockCustomPanel.PanelAngle Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlock.
        /// </summary>
        // *** Start programmer edit section *** (LegoBlockCustomPanel.Block CustomAttributes)

        // *** End programmer edit section *** (LegoBlockCustomPanel.Block CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Block"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlock Block
        {
            get
            {
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Block Get start)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Block Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlock result = this.fBlock;
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Block Get end)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Block Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Block Set start)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Block Set start)
                this.fBlock = value;
                // *** Start programmer edit section *** (LegoBlockCustomPanel.Block Set end)

                // *** End programmer edit section *** (LegoBlockCustomPanel.Block Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of LegoBlockCustomPanel.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfLegoBlockCustomPanel CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfLegoBlockCustomPanel CustomAttributes)
    public class DetailArrayOfLegoBlockCustomPanel : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoBlockCustomPanel members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfLegoBlockCustomPanel members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type LegoBlockCustomPanel by index.
        /// </summary>
        /// <summary>
        /// Adds object with type LegoBlockCustomPanel.
        /// </summary>
        public DetailArrayOfLegoBlockCustomPanel(NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlock fLegoBlock) : 
                base(typeof(LegoBlockCustomPanel), ((ICSSoft.STORMNET.DataObject)(fLegoBlock)))
        {
        }
        
        public NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockCustomPanel this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockCustomPanel)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.LegoBlockCustomPanel dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
