//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoDevice.
    /// </summary>
    // *** Start programmer edit section *** (LegoDevice CustomAttributes)

    // *** End programmer edit section *** (LegoDevice CustomAttributes)
    [PublishName("LegoDevice")]
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoDevice : NewPlatform.Flexberry.ORM.ODataService.Tests.BaseLegoBlock
    {

        private string fDescription;

        private bool fElectricity;

        // *** Start programmer edit section *** (LegoDevice CustomMembers)

        // *** End programmer edit section *** (LegoDevice CustomMembers)


        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (LegoDevice.Description CustomAttributes)

        // *** End programmer edit section *** (LegoDevice.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (LegoDevice.Description Get start)

                // *** End programmer edit section *** (LegoDevice.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (LegoDevice.Description Get end)

                // *** End programmer edit section *** (LegoDevice.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoDevice.Description Set start)

                // *** End programmer edit section *** (LegoDevice.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (LegoDevice.Description Set end)

                // *** End programmer edit section *** (LegoDevice.Description Set end)
            }
        }

        /// <summary>
        /// Electricity.
        /// </summary>
        // *** Start programmer edit section *** (LegoDevice.Electricity CustomAttributes)

        // *** End programmer edit section *** (LegoDevice.Electricity CustomAttributes)
        public virtual bool Electricity
        {
            get
            {
                // *** Start programmer edit section *** (LegoDevice.Electricity Get start)

                // *** End programmer edit section *** (LegoDevice.Electricity Get start)
                bool result = this.fElectricity;
                // *** Start programmer edit section *** (LegoDevice.Electricity Get end)

                // *** End programmer edit section *** (LegoDevice.Electricity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoDevice.Electricity Set start)

                // *** End programmer edit section *** (LegoDevice.Electricity Set start)
                this.fElectricity = value;
                // *** Start programmer edit section *** (LegoDevice.Electricity Set end)

                // *** End programmer edit section *** (LegoDevice.Electricity Set end)
            }
        }
    }
}

