//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// LegoBlockColor.
    /// </summary>
    // *** Start programmer edit section *** (LegoBlockColor CustomAttributes)

    // *** End programmer edit section *** (LegoBlockColor CustomAttributes)
    [PublishName("LegoBlockColor")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LegoBlockColor : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private int fColorNumber;
        
        // *** Start programmer edit section *** (LegoBlockColor CustomMembers)

        // *** End programmer edit section *** (LegoBlockColor CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (LegoBlockColor.Name CustomAttributes)

        // *** End programmer edit section *** (LegoBlockColor.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (LegoBlockColor.Name Get start)

                // *** End programmer edit section *** (LegoBlockColor.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (LegoBlockColor.Name Get end)

                // *** End programmer edit section *** (LegoBlockColor.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoBlockColor.Name Set start)

                // *** End programmer edit section *** (LegoBlockColor.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (LegoBlockColor.Name Set end)

                // *** End programmer edit section *** (LegoBlockColor.Name Set end)
            }
        }
        
        /// <summary>
        /// ColorNumber.
        /// </summary>
        // *** Start programmer edit section *** (LegoBlockColor.ColorNumber CustomAttributes)

        // *** End programmer edit section *** (LegoBlockColor.ColorNumber CustomAttributes)
        public virtual int ColorNumber
        {
            get
            {
                // *** Start programmer edit section *** (LegoBlockColor.ColorNumber Get start)

                // *** End programmer edit section *** (LegoBlockColor.ColorNumber Get start)
                int result = this.fColorNumber;
                // *** Start programmer edit section *** (LegoBlockColor.ColorNumber Get end)

                // *** End programmer edit section *** (LegoBlockColor.ColorNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (LegoBlockColor.ColorNumber Set start)

                // *** End programmer edit section *** (LegoBlockColor.ColorNumber Set start)
                this.fColorNumber = value;
                // *** Start programmer edit section *** (LegoBlockColor.ColorNumber Set end)

                // *** End programmer edit section *** (LegoBlockColor.ColorNumber Set end)
            }
        }
    }
}
