//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// MainClass.
    /// </summary>
    // *** Start programmer edit section *** (MainClass CustomAttributes)

    // *** End programmer edit section *** (MainClass CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class MainClass : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private NewPlatform.Flexberry.ORM.ODataService.Tests.AgrClass1 fAgrClass1;
        
        // *** Start programmer edit section *** (MainClass CustomMembers)

        // *** End programmer edit section *** (MainClass CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (MainClass.Name CustomAttributes)

        // *** End programmer edit section *** (MainClass.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (MainClass.Name Get start)

                // *** End programmer edit section *** (MainClass.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (MainClass.Name Get end)

                // *** End programmer edit section *** (MainClass.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MainClass.Name Set start)

                // *** End programmer edit section *** (MainClass.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (MainClass.Name Set end)

                // *** End programmer edit section *** (MainClass.Name Set end)
            }
        }
        
        /// <summary>
        /// MainClass.
        /// </summary>
        // *** Start programmer edit section *** (MainClass.AgrClass1 CustomAttributes)

        // *** End programmer edit section *** (MainClass.AgrClass1 CustomAttributes)
        [PropertyStorage(new string[] {
                "AgrClass1"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.AgrClass1 AgrClass1
        {
            get
            {
                // *** Start programmer edit section *** (MainClass.AgrClass1 Get start)

                // *** End programmer edit section *** (MainClass.AgrClass1 Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.AgrClass1 result = this.fAgrClass1;
                // *** Start programmer edit section *** (MainClass.AgrClass1 Get end)

                // *** End programmer edit section *** (MainClass.AgrClass1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MainClass.AgrClass1 Set start)

                // *** End programmer edit section *** (MainClass.AgrClass1 Set start)
                this.fAgrClass1 = value;
                // *** Start programmer edit section *** (MainClass.AgrClass1 Set end)

                // *** End programmer edit section *** (MainClass.AgrClass1 Set end)
            }
        }
    }
}
