//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Master.
    /// </summary>
    // *** Start programmer edit section *** (Master CustomAttributes)

    // *** End programmer edit section *** (Master CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Master : ICSSoft.STORMNET.DataObject
    {

        private string fproperty;

        // *** Start programmer edit section *** (Master CustomMembers)

        // *** End programmer edit section *** (Master CustomMembers)


        /// <summary>
        /// property.
        /// </summary>
        // *** Start programmer edit section *** (Master.property CustomAttributes)

        // *** End programmer edit section *** (Master.property CustomAttributes)
        [StrLen(255)]
        public virtual string property
        {
            get
            {
                // *** Start programmer edit section *** (Master.property Get start)

                // *** End programmer edit section *** (Master.property Get start)
                string result = this.fproperty;
                // *** Start programmer edit section *** (Master.property Get end)

                // *** End programmer edit section *** (Master.property Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Master.property Set start)

                // *** End programmer edit section *** (Master.property Set start)
                this.fproperty = value;
                // *** Start programmer edit section *** (Master.property Set end)

                // *** End programmer edit section *** (Master.property Set end)
            }
        }
    }
}

