//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// SecondLevel2.
    /// </summary>
    // *** Start programmer edit section *** (SecondLevel2 CustomAttributes)

    // *** End programmer edit section *** (SecondLevel2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class SecondLevel2 : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1 fSecondLevel1;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel fFirstLevel;

        // *** Start programmer edit section *** (SecondLevel2 CustomMembers)

        // *** End programmer edit section *** (SecondLevel2 CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (SecondLevel2.Name CustomAttributes)

        // *** End programmer edit section *** (SecondLevel2.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (SecondLevel2.Name Get start)

                // *** End programmer edit section *** (SecondLevel2.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (SecondLevel2.Name Get end)

                // *** End programmer edit section *** (SecondLevel2.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SecondLevel2.Name Set start)

                // *** End programmer edit section *** (SecondLevel2.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (SecondLevel2.Name Set end)

                // *** End programmer edit section *** (SecondLevel2.Name Set end)
            }
        }

        /// <summary>
        /// SecondLevel2.
        /// </summary>
        // *** Start programmer edit section *** (SecondLevel2.SecondLevel1 CustomAttributes)

        // *** End programmer edit section *** (SecondLevel2.SecondLevel1 CustomAttributes)
        [PropertyStorage("SecondLevel1")]
        [TypeUsage(new string[] {
                "NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1",
                "NewPlatform.Flexberry.ORM.ODataService.Tests.TestClass"})]
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1 SecondLevel1
        {
            get
            {
                // *** Start programmer edit section *** (SecondLevel2.SecondLevel1 Get start)

                // *** End programmer edit section *** (SecondLevel2.SecondLevel1 Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1 result = this.fSecondLevel1;
                // *** Start programmer edit section *** (SecondLevel2.SecondLevel1 Get end)

                // *** End programmer edit section *** (SecondLevel2.SecondLevel1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SecondLevel2.SecondLevel1 Set start)

                // *** End programmer edit section *** (SecondLevel2.SecondLevel1 Set start)
                this.fSecondLevel1 = value;
                // *** Start programmer edit section *** (SecondLevel2.SecondLevel1 Set end)

                // *** End programmer edit section *** (SecondLevel2.SecondLevel1 Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel.
        /// </summary>
        // *** Start programmer edit section *** (SecondLevel2.FirstLevel CustomAttributes)

        // *** End programmer edit section *** (SecondLevel2.FirstLevel CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "FirstLevel"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel FirstLevel
        {
            get
            {
                // *** Start programmer edit section *** (SecondLevel2.FirstLevel Get start)

                // *** End programmer edit section *** (SecondLevel2.FirstLevel Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel result = this.fFirstLevel;
                // *** Start programmer edit section *** (SecondLevel2.FirstLevel Get end)

                // *** End programmer edit section *** (SecondLevel2.FirstLevel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SecondLevel2.FirstLevel Set start)

                // *** End programmer edit section *** (SecondLevel2.FirstLevel Set start)
                this.fFirstLevel = value;
                // *** Start programmer edit section *** (SecondLevel2.FirstLevel Set end)

                // *** End programmer edit section *** (SecondLevel2.FirstLevel Set end)
            }
        }
    }

    /// <summary>
    /// Detail array of SecondLevel2.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSecondLevel2 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSecondLevel2 CustomAttributes)
    public class DetailArrayOfSecondLevel2 : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel2 members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel2 members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type SecondLevel2 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type SecondLevel2.
        /// </summary>
        public DetailArrayOfSecondLevel2(NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel fFirstLevel) : 
                base(typeof(SecondLevel2), ((ICSSoft.STORMNET.DataObject)(fFirstLevel)))
        {
        }

        public NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel2 this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel2)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel2 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

