//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// SecondLevel1.
    /// </summary>
    // *** Start programmer edit section *** (SecondLevel1 CustomAttributes)

    // *** End programmer edit section *** (SecondLevel1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class SecondLevel1 : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel fFirstLevel;

        // *** Start programmer edit section *** (SecondLevel1 CustomMembers)

        // *** End programmer edit section *** (SecondLevel1 CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (SecondLevel1.Name CustomAttributes)

        // *** End programmer edit section *** (SecondLevel1.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (SecondLevel1.Name Get start)

                // *** End programmer edit section *** (SecondLevel1.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (SecondLevel1.Name Get end)

                // *** End programmer edit section *** (SecondLevel1.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SecondLevel1.Name Set start)

                // *** End programmer edit section *** (SecondLevel1.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (SecondLevel1.Name Set end)

                // *** End programmer edit section *** (SecondLevel1.Name Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel.
        /// </summary>
        // *** Start programmer edit section *** (SecondLevel1.FirstLevel CustomAttributes)

        // *** End programmer edit section *** (SecondLevel1.FirstLevel CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "FirstLevel"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel FirstLevel
        {
            get
            {
                // *** Start programmer edit section *** (SecondLevel1.FirstLevel Get start)

                // *** End programmer edit section *** (SecondLevel1.FirstLevel Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel result = this.fFirstLevel;
                // *** Start programmer edit section *** (SecondLevel1.FirstLevel Get end)

                // *** End programmer edit section *** (SecondLevel1.FirstLevel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SecondLevel1.FirstLevel Set start)

                // *** End programmer edit section *** (SecondLevel1.FirstLevel Set start)
                this.fFirstLevel = value;
                // *** Start programmer edit section *** (SecondLevel1.FirstLevel Set end)

                // *** End programmer edit section *** (SecondLevel1.FirstLevel Set end)
            }
        }
    }

    /// <summary>
    /// Detail array of SecondLevel1.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSecondLevel1 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSecondLevel1 CustomAttributes)
    public class DetailArrayOfSecondLevel1 : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel1 members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfSecondLevel1 members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type SecondLevel1 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type SecondLevel1.
        /// </summary>
        public DetailArrayOfSecondLevel1(NewPlatform.Flexberry.ORM.ODataService.Tests.FirstLevel fFirstLevel) : 
                base(typeof(SecondLevel1), ((ICSSoft.STORMNET.DataObject)(fFirstLevel)))
        {
        }

        public NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1 this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

