//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// TestClass.
    /// </summary>
    // *** Start programmer edit section *** (TestClass CustomAttributes)

    // *** End programmer edit section *** (TestClass CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class TestClass : NewPlatform.Flexberry.ORM.ODataService.Tests.SecondLevel1
    {

        private NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfThirdLevel fThirdLevel;

        // *** Start programmer edit section *** (TestClass CustomMembers)

        // *** End programmer edit section *** (TestClass CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (TestClass.Name CustomAttributes)

        // *** End programmer edit section *** (TestClass.Name CustomAttributes)
        [StrLen(255)]
        public override string Name
        {
            get
            {
                // *** Start programmer edit section *** (TestClass.Name Get start)

                // *** End programmer edit section *** (TestClass.Name Get start)
                string result = base.Name;
                // *** Start programmer edit section *** (TestClass.Name Get end)

                // *** End programmer edit section *** (TestClass.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TestClass.Name Set start)

                // *** End programmer edit section *** (TestClass.Name Set start)
                base.Name = value;
                // *** Start programmer edit section *** (TestClass.Name Set end)

                // *** End programmer edit section *** (TestClass.Name Set end)
            }
        }

        /// <summary>
        /// TestClass.
        /// </summary>
        // *** Start programmer edit section *** (TestClass.ThirdLevel CustomAttributes)

        // *** End programmer edit section *** (TestClass.ThirdLevel CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfThirdLevel ThirdLevel
        {
            get
            {
                // *** Start programmer edit section *** (TestClass.ThirdLevel Get start)

                // *** End programmer edit section *** (TestClass.ThirdLevel Get start)
                if ((this.fThirdLevel == null))
                {
                    this.fThirdLevel = new NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfThirdLevel(this);
                }
                NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfThirdLevel result = this.fThirdLevel;
                // *** Start programmer edit section *** (TestClass.ThirdLevel Get end)

                // *** End programmer edit section *** (TestClass.ThirdLevel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (TestClass.ThirdLevel Set start)

                // *** End programmer edit section *** (TestClass.ThirdLevel Set start)
                this.fThirdLevel = value;
                // *** Start programmer edit section *** (TestClass.ThirdLevel Set end)

                // *** End programmer edit section *** (TestClass.ThirdLevel Set end)
            }
        }
    }
}

