//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ThirdLevel.
    /// </summary>
    // *** Start programmer edit section *** (ThirdLevel CustomAttributes)

    // *** End programmer edit section *** (ThirdLevel CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ThirdLevel : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.TestClass fTestClass;

        // *** Start programmer edit section *** (ThirdLevel CustomMembers)

        // *** End programmer edit section *** (ThirdLevel CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ThirdLevel.Name CustomAttributes)

        // *** End programmer edit section *** (ThirdLevel.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ThirdLevel.Name Get start)

                // *** End programmer edit section *** (ThirdLevel.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ThirdLevel.Name Get end)

                // *** End programmer edit section *** (ThirdLevel.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ThirdLevel.Name Set start)

                // *** End programmer edit section *** (ThirdLevel.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ThirdLevel.Name Set end)

                // *** End programmer edit section *** (ThirdLevel.Name Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.Flexberry.ORM.ODataService.Tests.TestClass.
        /// </summary>
        // *** Start programmer edit section *** (ThirdLevel.TestClass CustomAttributes)

        // *** End programmer edit section *** (ThirdLevel.TestClass CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "TestClass"})]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.TestClass TestClass
        {
            get
            {
                // *** Start programmer edit section *** (ThirdLevel.TestClass Get start)

                // *** End programmer edit section *** (ThirdLevel.TestClass Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.TestClass result = this.fTestClass;
                // *** Start programmer edit section *** (ThirdLevel.TestClass Get end)

                // *** End programmer edit section *** (ThirdLevel.TestClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ThirdLevel.TestClass Set start)

                // *** End programmer edit section *** (ThirdLevel.TestClass Set start)
                this.fTestClass = value;
                // *** Start programmer edit section *** (ThirdLevel.TestClass Set end)

                // *** End programmer edit section *** (ThirdLevel.TestClass Set end)
            }
        }
    }

    /// <summary>
    /// Detail array of ThirdLevel.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfThirdLevel CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfThirdLevel CustomAttributes)
    public class DetailArrayOfThirdLevel : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfThirdLevel members)

        // *** End programmer edit section *** (NewPlatform.Flexberry.ORM.ODataService.Tests.DetailArrayOfThirdLevel members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ThirdLevel by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ThirdLevel.
        /// </summary>
        public DetailArrayOfThirdLevel(NewPlatform.Flexberry.ORM.ODataService.Tests.TestClass fTestClass) : 
                base(typeof(ThirdLevel), ((ICSSoft.STORMNET.DataObject)(fTestClass)))
        {
        }

        public NewPlatform.Flexberry.ORM.ODataService.Tests.ThirdLevel this[int index]
        {
            get
            {
                return ((NewPlatform.Flexberry.ORM.ODataService.Tests.ThirdLevel)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(NewPlatform.Flexberry.ORM.ODataService.Tests.ThirdLevel dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

