//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// tTip.
    /// </summary>
    // *** Start programmer edit section *** (tTip CustomAttributes)

    // *** End programmer edit section *** (tTip CustomAttributes)
    public enum tTip
    {

        // *** Start programmer edit section *** (tTip.sedan CustomAttributes)

        // *** End programmer edit section *** (tTip.sedan CustomAttributes)
        sedan,

        // *** Start programmer edit section *** (tTip.cabriolet CustomAttributes)

        // *** End programmer edit section *** (tTip.cabriolet CustomAttributes)
        cabriolet,

        // *** Start programmer edit section *** (tTip.coupe CustomAttributes)

        // *** End programmer edit section *** (tTip.coupe CustomAttributes)
        coupe,

        // *** Start programmer edit section *** (tTip.pickup CustomAttributes)

        // *** End programmer edit section *** (tTip.pickup CustomAttributes)
        pickup,

        // *** Start programmer edit section *** (tTip.crossover CustomAttributes)

        // *** End programmer edit section *** (tTip.crossover CustomAttributes)
        crossover,

        // *** Start programmer edit section *** (tTip.limousine CustomAttributes)

        // *** End programmer edit section *** (tTip.limousine CustomAttributes)
        limousine,

        // *** Start programmer edit section *** (tTip.roadster CustomAttributes)

        // *** End programmer edit section *** (tTip.roadster CustomAttributes)
        roadster,

        // *** Start programmer edit section *** (tTip.minivan CustomAttributes)

        // *** End programmer edit section *** (tTip.minivan CustomAttributes)
        minivan,
    }
}

