//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пол.
    /// </summary>
    // *** Start programmer edit section *** (tПол CustomAttributes)

    // *** End programmer edit section *** (tПол CustomAttributes)
    public enum tПол
    {

        // *** Start programmer edit section *** (tПол.Мужской CustomAttributes)

        // *** End programmer edit section *** (tПол.Мужской CustomAttributes)
        Мужской,

        // *** Start programmer edit section *** (tПол.Женский CustomAttributes)

        // *** End programmer edit section *** (tПол.Женский CustomAttributes)
        Женский,

        // *** Start programmer edit section *** (tПол.НеПонятно CustomAttributes)

        // *** End programmer edit section *** (tПол.НеПонятно CustomAttributes)
        НеПонятно,
    }
}

