//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ДочернийКласс.
    /// </summary>
    // *** Start programmer edit section *** (ДочернийКласс CustomAttributes)
    [ClassStorage("ДочернийКласс")]
    // *** End programmer edit section *** (ДочернийКласс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДочернийКлассE", new string[] {
            "ChildProperty",
            "PropertyEnum",
            "PropertyBool",
            "PropertyInt",
            "PropertyDateTime",
            "PropertyString",
            "PropertyFloat",
            "PropertyDouble",
            "PropertyDecimal",
            "PropertySystemNullableDateTime",
            "PropertySystemNullableInt",
            "PropertySystemNullableGuid",
            "PropertySystemNullableDecimal",
            "PropertyStormnetNullableDateTime",
            "PropertyStormnetNullableInt",
            "PropertyStormnetKeyGuid",
            "PropertyStormnetNullableDecimal",
            "PropertyStormnetPartliedDate",
            "PropertyStormnetContact",
            "PropertyStormnetBlob",
            "PropertyStormnetEvent",
            "PropertyStormnetGeoData",
            "PropertyStormnetImage",
            "PropertyStormnetWebFile",
            "PropertyStormnetFile"})]
    public class ДочернийКласс : NewPlatform.Flexberry.ORM.ODataService.Tests.КлассСМножествомТипов
    {

        private string fChildProperty;

        // *** Start programmer edit section *** (ДочернийКласс CustomMembers)

        // *** End programmer edit section *** (ДочернийКласс CustomMembers)


        /// <summary>
        /// ChildProperty.
        /// </summary>
        // *** Start programmer edit section *** (ДочернийКласс.ChildProperty CustomAttributes)

        // *** End programmer edit section *** (ДочернийКласс.ChildProperty CustomAttributes)
        [StrLen(255)]
        public virtual string ChildProperty
        {
            get
            {
                // *** Start programmer edit section *** (ДочернийКласс.ChildProperty Get start)

                // *** End programmer edit section *** (ДочернийКласс.ChildProperty Get start)
                string result = this.fChildProperty;
                // *** Start programmer edit section *** (ДочернийКласс.ChildProperty Get end)

                // *** End programmer edit section *** (ДочернийКласс.ChildProperty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДочернийКласс.ChildProperty Set start)

                // *** End programmer edit section *** (ДочернийКласс.ChildProperty Set start)
                this.fChildProperty = value;
                // *** Start programmer edit section *** (ДочернийКласс.ChildProperty Set end)

                // *** End programmer edit section *** (ДочернийКласс.ChildProperty Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ДочернийКлассE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДочернийКлассE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДочернийКлассE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.ДочернийКласс));
                }
            }
        }
    }
}

