//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// КлассNotStored.
    /// </summary>
    // *** Start programmer edit section *** (КлассNotStored CustomAttributes)

    // *** End programmer edit section *** (КлассNotStored CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассNotStoredE", new string[] {
            "StrAttr"})]
    public class КлассNotStored : ICSSoft.STORMNET.DataObject
    {

        private string fStrAttr;

        // *** Start programmer edit section *** (КлассNotStored CustomMembers)

        // *** End programmer edit section *** (КлассNotStored CustomMembers)


        /// <summary>
        /// StrAttr.
        /// </summary>
        // *** Start programmer edit section *** (КлассNotStored.StrAttr CustomAttributes)

        // *** End programmer edit section *** (КлассNotStored.StrAttr CustomAttributes)
        [StrLen(255)]
        public virtual string StrAttr
        {
            get
            {
                // *** Start programmer edit section *** (КлассNotStored.StrAttr Get start)

                // *** End programmer edit section *** (КлассNotStored.StrAttr Get start)
                string result = this.fStrAttr;
                // *** Start programmer edit section *** (КлассNotStored.StrAttr Get end)

                // *** End programmer edit section *** (КлассNotStored.StrAttr Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассNotStored.StrAttr Set start)

                // *** End programmer edit section *** (КлассNotStored.StrAttr Set start)
                this.fStrAttr = value;
                // *** Start programmer edit section *** (КлассNotStored.StrAttr Set end)

                // *** End programmer edit section *** (КлассNotStored.StrAttr Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "КлассNotStoredE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассNotStoredE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассNotStoredE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.КлассNotStored));
                }
            }
        }
    }
}

