//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Котенок.
    /// </summary>
    // *** Start programmer edit section *** (Котенок CustomAttributes)

    // *** End programmer edit section *** (Котенок CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Котенок : ICSSoft.STORMNET.DataObject
    {

        private int fГлупость;

        private string fКличкаКотенка;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.Кошка fКошка;

        // *** Start programmer edit section *** (Котенок CustomMembers)

        // *** End programmer edit section *** (Котенок CustomMembers)


        /// <summary>
        /// Глупость.
        /// </summary>
        // *** Start programmer edit section *** (Котенок.Глупость CustomAttributes)

        // *** End programmer edit section *** (Котенок.Глупость CustomAttributes)
        public virtual int Глупость
        {
            get
            {
                // *** Start programmer edit section *** (Котенок.Глупость Get start)

                // *** End programmer edit section *** (Котенок.Глупость Get start)
                int result = this.fГлупость;
                // *** Start programmer edit section *** (Котенок.Глупость Get end)

                // *** End programmer edit section *** (Котенок.Глупость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Котенок.Глупость Set start)

                // *** End programmer edit section *** (Котенок.Глупость Set start)
                this.fГлупость = value;
                // *** Start programmer edit section *** (Котенок.Глупость Set end)

                // *** End programmer edit section *** (Котенок.Глупость Set end)
            }
        }

        /// <summary>
        /// КличкаКотенка.
        /// </summary>
        // *** Start programmer edit section *** (Котенок.КличкаКотенка CustomAttributes)

        // *** End programmer edit section *** (Котенок.КличкаКотенка CustomAttributes)
        [StrLen(255)]
        public virtual string КличкаКотенка
        {
            get
            {
                // *** Start programmer edit section *** (Котенок.КличкаКотенка Get start)

                // *** End programmer edit section *** (Котенок.КличкаКотенка Get start)
                string result = this.fКличкаКотенка;
                // *** Start programmer edit section *** (Котенок.КличкаКотенка Get end)

                // *** End programmer edit section *** (Котенок.КличкаКотенка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Котенок.КличкаКотенка Set start)

                // *** End programmer edit section *** (Котенок.КличкаКотенка Set start)
                this.fКличкаКотенка = value;
                // *** Start programmer edit section *** (Котенок.КличкаКотенка Set end)

                // *** End programmer edit section *** (Котенок.КличкаКотенка Set end)
            }
        }

        /// <summary>
        /// Котенок.
        /// </summary>
        // *** Start programmer edit section *** (Котенок.Кошка CustomAttributes)

        // *** End programmer edit section *** (Котенок.Кошка CustomAttributes)
        [NotNull()]
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Кошка Кошка
        {
            get
            {
                // *** Start programmer edit section *** (Котенок.Кошка Get start)

                // *** End programmer edit section *** (Котенок.Кошка Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Кошка result = this.fКошка;
                // *** Start programmer edit section *** (Котенок.Кошка Get end)

                // *** End programmer edit section *** (Котенок.Кошка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Котенок.Кошка Set start)

                // *** End programmer edit section *** (Котенок.Кошка Set start)
                this.fКошка = value;
                // *** Start programmer edit section *** (Котенок.Кошка Set end)

                // *** End programmer edit section *** (Котенок.Кошка Set end)
            }
        }
    }
}

