//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Мастер2.
    /// </summary>
    // *** Start programmer edit section *** (Мастер2 CustomAttributes)

    // *** End programmer edit section *** (Мастер2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Мастер2 : ICSSoft.STORMNET.DataObject
    {

        private int fсвойство2;

        // *** Start programmer edit section *** (Мастер2 CustomMembers)

        // *** End programmer edit section *** (Мастер2 CustomMembers)


        /// <summary>
        /// свойство2.
        /// </summary>
        // *** Start programmer edit section *** (Мастер2.свойство2 CustomAttributes)
        [PublishName("Property2Alias")]
        // *** End programmer edit section *** (Мастер2.свойство2 CustomAttributes)
        public virtual int свойство2
        {
            get
            {
                // *** Start programmer edit section *** (Мастер2.свойство2 Get start)

                // *** End programmer edit section *** (Мастер2.свойство2 Get start)
                int result = this.fсвойство2;
                // *** Start programmer edit section *** (Мастер2.свойство2 Get end)

                // *** End programmer edit section *** (Мастер2.свойство2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Мастер2.свойство2 Set start)

                // *** End programmer edit section *** (Мастер2.свойство2 Set start)
                this.fсвойство2 = value;
                // *** Start programmer edit section *** (Мастер2.свойство2 Set end)

                // *** End programmer edit section *** (Мастер2.свойство2 Set end)
            }
        }
    }
}

