//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Порода.
    /// </summary>
    // *** Start programmer edit section *** (Порода CustomAttributes)

    // *** End programmer edit section *** (Порода CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПородаE", new string[] {
            "Название",
            "ТипПороды",
            "ТипПороды.Название",
            "Иерархия",
            "Иерархия.Название"}, Hidden=new string[] {
            "ТипПороды",
            "Иерархия"})]
    public class Порода : ICSSoft.STORMNET.DataObject
    {

        private string fНазвание;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.Порода fИерархия;

        private NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПороды fТипПороды;

        // *** Start programmer edit section *** (Порода CustomMembers)

        // *** End programmer edit section *** (Порода CustomMembers)


        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Порода.Название CustomAttributes)

        // *** End programmer edit section *** (Порода.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Порода.Название Get start)

                // *** End programmer edit section *** (Порода.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Порода.Название Get end)

                // *** End programmer edit section *** (Порода.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Порода.Название Set start)

                // *** End programmer edit section *** (Порода.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Порода.Название Set end)

                // *** End programmer edit section *** (Порода.Название Set end)
            }
        }

        /// <summary>
        /// Порода.
        /// </summary>
        // *** Start programmer edit section *** (Порода.Иерархия CustomAttributes)

        // *** End programmer edit section *** (Порода.Иерархия CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.Порода Иерархия
        {
            get
            {
                // *** Start programmer edit section *** (Порода.Иерархия Get start)

                // *** End programmer edit section *** (Порода.Иерархия Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.Порода result = this.fИерархия;
                // *** Start programmer edit section *** (Порода.Иерархия Get end)

                // *** End programmer edit section *** (Порода.Иерархия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Порода.Иерархия Set start)

                // *** End programmer edit section *** (Порода.Иерархия Set start)
                this.fИерархия = value;
                // *** Start programmer edit section *** (Порода.Иерархия Set end)

                // *** End programmer edit section *** (Порода.Иерархия Set end)
            }
        }

        /// <summary>
        /// Порода.
        /// </summary>
        // *** Start programmer edit section *** (Порода.ТипПороды CustomAttributes)

        // *** End programmer edit section *** (Порода.ТипПороды CustomAttributes)
        public virtual NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПороды ТипПороды
        {
            get
            {
                // *** Start programmer edit section *** (Порода.ТипПороды Get start)

                // *** End programmer edit section *** (Порода.ТипПороды Get start)
                NewPlatform.Flexberry.ORM.ODataService.Tests.ТипПороды result = this.fТипПороды;
                // *** Start programmer edit section *** (Порода.ТипПороды Get end)

                // *** End programmer edit section *** (Порода.ТипПороды Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Порода.ТипПороды Set start)

                // *** End programmer edit section *** (Порода.ТипПороды Set start)
                this.fТипПороды = value;
                // *** Start programmer edit section *** (Порода.ТипПороды Set end)

                // *** End programmer edit section *** (Порода.ТипПороды Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ПородаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПородаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПородаE", typeof(NewPlatform.Flexberry.ORM.ODataService.Tests.Порода));
                }
            }
        }
    }
}

