//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сторона.
    /// </summary>
    // *** Start programmer edit section *** (Сторона CustomAttributes)

    // *** End programmer edit section *** (Сторона CustomAttributes)
    public enum Сторона
    {

        // *** Start programmer edit section *** (Сторона.НетЗначения CustomAttributes)

        // *** End programmer edit section *** (Сторона.НетЗначения CustomAttributes)
        НетЗначения,

        // *** Start programmer edit section *** (Сторона.Левая CustomAttributes)

        // *** End programmer edit section *** (Сторона.Левая CustomAttributes)
        Левая,

        // *** Start programmer edit section *** (Сторона.Правая CustomAttributes)

        // *** End programmer edit section *** (Сторона.Правая CustomAttributes)
        Правая,
    }
}

