//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипПерелома.
    /// </summary>
    // *** Start programmer edit section *** (ТипПерелома CustomAttributes)

    // *** End programmer edit section *** (ТипПерелома CustomAttributes)
    public enum ТипПерелома
    {

        // *** Start programmer edit section *** (ТипПерелома.Открытый CustomAttributes)

        // *** End programmer edit section *** (ТипПерелома.Открытый CustomAttributes)
        Открытый,

        // *** Start programmer edit section *** (ТипПерелома.Закрытый CustomAttributes)

        // *** End programmer edit section *** (ТипПерелома.Закрытый CustomAttributes)
        Закрытый,
    }
}

