//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипКошки.
    /// </summary>
    // *** Start programmer edit section *** (ТипКошки CustomAttributes)

    // *** End programmer edit section *** (ТипКошки CustomAttributes)
    public enum ТипКошки
    {

        // *** Start programmer edit section *** (ТипКошки.НетЗначения CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.НетЗначения CustomAttributes)
        НетЗначения,

        // *** Start programmer edit section *** (ТипКошки.Дикая CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.Дикая CustomAttributes)
        Дикая,

        // *** Start programmer edit section *** (ТипКошки.Домашняя CustomAttributes)

        // *** End programmer edit section *** (ТипКошки.Домашняя CustomAttributes)
        Домашняя,
    }
}

