//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипЛапы.
    /// </summary>
    // *** Start programmer edit section *** (ТипЛапы CustomAttributes)

    // *** End programmer edit section *** (ТипЛапы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ТипЛапы : ICSSoft.STORMNET.DataObject
    {

        private bool fАктуально;

        private string fНазвание;

        // *** Start programmer edit section *** (ТипЛапы CustomMembers)

        // *** End programmer edit section *** (ТипЛапы CustomMembers)


        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (ТипЛапы.Актуально CustomAttributes)

        // *** End programmer edit section *** (ТипЛапы.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                // *** Start programmer edit section *** (ТипЛапы.Актуально Get start)

                // *** End programmer edit section *** (ТипЛапы.Актуально Get start)
                bool result = this.fАктуально;
                // *** Start programmer edit section *** (ТипЛапы.Актуально Get end)

                // *** End programmer edit section *** (ТипЛапы.Актуально Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипЛапы.Актуально Set start)

                // *** End programmer edit section *** (ТипЛапы.Актуально Set start)
                this.fАктуально = value;
                // *** Start programmer edit section *** (ТипЛапы.Актуально Set end)

                // *** End programmer edit section *** (ТипЛапы.Актуально Set end)
            }
        }

        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ТипЛапы.Название CustomAttributes)

        // *** End programmer edit section *** (ТипЛапы.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ТипЛапы.Название Get start)

                // *** End programmer edit section *** (ТипЛапы.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ТипЛапы.Название Get end)

                // *** End programmer edit section *** (ТипЛапы.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипЛапы.Название Set start)

                // *** End programmer edit section *** (ТипЛапы.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ТипЛапы.Название Set end)

                // *** End programmer edit section *** (ТипЛапы.Название Set end)
            }
        }
    }
}

