//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.ORM.ODataService.Tests
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Цифра.
    /// </summary>
    // *** Start programmer edit section *** (Цифра CustomAttributes)

    // *** End programmer edit section *** (Цифра CustomAttributes)
    public enum Цифра
    {

        // *** Start programmer edit section *** (Цифра.Ноль CustomAttributes)

        // *** End programmer edit section *** (Цифра.Ноль CustomAttributes)
        Ноль,

        // *** Start programmer edit section *** (Цифра.Один CustomAttributes)

        // *** End programmer edit section *** (Цифра.Один CustomAttributes)
        Один,

        // *** Start programmer edit section *** (Цифра.Два CustomAttributes)

        // *** End programmer edit section *** (Цифра.Два CustomAttributes)
        Два,

        // *** Start programmer edit section *** (Цифра.Три CustomAttributes)

        // *** End programmer edit section *** (Цифра.Три CustomAttributes)
        Три,

        // *** Start programmer edit section *** (Цифра.Четыре CustomAttributes)

        // *** End programmer edit section *** (Цифра.Четыре CustomAttributes)
        Четыре,

        // *** Start programmer edit section *** (Цифра.Пять CustomAttributes)

        // *** End programmer edit section *** (Цифра.Пять CustomAttributes)
        Пять,

        // *** Start programmer edit section *** (Цифра.Шесть CustomAttributes)

        // *** End programmer edit section *** (Цифра.Шесть CustomAttributes)
        Шесть,

        // *** Start programmer edit section *** (Цифра.Семь CustomAttributes)

        // *** End programmer edit section *** (Цифра.Семь CustomAttributes)
        Семь,

        // *** Start programmer edit section *** (Цифра.Восемь CustomAttributes)

        // *** End programmer edit section *** (Цифра.Восемь CustomAttributes)
        Восемь,

        // *** Start programmer edit section *** (Цифра.Девять CustomAttributes)

        // *** End programmer edit section *** (Цифра.Девять CustomAttributes)
        Девять,
    }
}

