# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop-v5.2 branch
  push:
    branches: [ develop-v5.2 ]
  pull_request:
    branches: [ develop-v5.2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install mono
      - name: Install mono
        run: sudo apt-get install -y mono-devel

      # Runs a set of commands using the runners shell
      - name: Compile OData
        run: |
          nuget restore NewPlatform.Flexberry.ORM.ODataService.sln
          nuget restore NewPlatform.Flexberry.ORM.ODataService.sln
          msbuild /p:Configuration=Debug NewPlatform.Flexberry.ORM.ODataService.sln
          mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/bin/Debug/NewPlatform.Flexberry.ORM.ODataService.Tests.dll
              
